### ISSUE TITLE
Images in reports

### ISSUE THREAD

**Issue by nderwin** [quarkiverse/quarkus-jasperreports#127]
Images do not appear to be loading in reports - either as a file in the project, as a static resource served by the project, or an external image from a URL.  See https://github.com/nderwin-forks/quarkus-jasperreports/tree/feature/images-in-reports for examples.

The unit test is currently failing because the host URL needs to be dynamically passed to the report instead of it being hard-coded as `http://localhost:8080`.

**Comment by melloware** [comment]
can you submit the PR as draft so I can look?

**Comment by nderwin** [comment]
Sure;  in the 6.x version, I had solved this with changes to the repository service;  the current one works much the same as mine did for external images, but that didn't seem to be working either.

If you fire up the integration-tests project in dev mode, then it'll produce the report, but all of the `img` tags have an empty string for the `src` attribute.

**Comment by melloware** [comment]
Thanks i will take a look.

**Comment by nderwin** [comment]
I had just started looking at this, so not sure what the PDF renderer does.  I'll also eventually need the XLSX output to work.

**Comment by melloware** [comment]
ok i am looking at the samples. And they use SimpleHtmlExporter to export to a jrpint file in their the exporter it does this

```java
private void setFileHandlers(File destFile)
	{
		File resourcesDir = new File(destFile.getParent(), destFile.getName() + "_files");
		String pathPattern = resourcesDir.getName() + "/{0}";
		resourceHandler = new FileHtmlResourceHandler(resourcesDir, pathPattern);
		imageHandler = resourceHandler;
		fontHandler = resourceHandler;
	}
```

So its registering a default File handler for images?

**Comment by melloware** [comment]
Also when I step through the debugger i see it loading the images properly in `JRImageLoader`

**Comment by nderwin** [comment]
Good news - PDF and XLSX output works fine as-is, but that makes sense because the images are embedded.  HTML output will need some more work to provide an endpoint that serves the generated image files (like `img_0_0_2.svg` or `img_0_0_4.gif`).

**Comment by melloware** [comment]
2 things.  

1. You should add one of these as a Hyperlink like... so we can kill two birds with one stone and test Hyperlink as well.

https://github.com/TIBCOSoftware/jasperreports/blob/a8ec0e6cbbf04d36878c8f783f10c2ff88afeff5/demo/samples/hyperlink/reports/HyperlinkReport.jrxml#L27C4-L31C14

2. If you want to Add a WEBP file you have to add this dependency to runtime module.

```xml
<dependency>
			<groupId>com.twelvemonkeys.imageio</groupId>
			<artifactId>imageio-webp</artifactId>
			<version>3.9.4</version>
</dependency>
```

https://github.com/TIBCOSoftware/jasperreports/blob/a8ec0e6cbbf04d36878c8f783f10c2ff88afeff5/demo/samples/images/reports/ImagesReport.jrxml#L210-L229

**Comment by nderwin** [comment]
<maniacal laugh>
Figured out how to use the `FileHtmlResourceHandler` to dump the images for the HTML output into a temp folder, then provided an endpoint to serve them.  WEBP can be another iteration.

**Comment by melloware** [comment]
Closing this we don't need to test WEBP if that JAR  or any other TwelveMonkeys JAR is on the classpath it just registers with `javax.imageio`
