### ISSUE TITLE
HotReload testing

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-jasperreports#130]
I was seeing if I edited a JRXML file that I would expect that would trigger a recompile and I am not seeing that?  @nderwin are you?

**Comment by nderwin** [comment]
@melloware No, I'm not seeing it now either.  It's triggering a reload of Quarkus, but not a recompile of the report file.

**Comment by melloware** [comment]
i will take a look at this one.  I think i know how to fix it.
