### ISSUE TITLE
1.0.0 Release?

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-jasperreports#136]
@nderwin @Postremus are there any missing features or should we do a 1.0.0 release?  Here is what has been tested in Native mode.

**Datasources:**
- [x] XML
- [x] CSV
- [x] JSON
- [x] Database

**Exporters:**
- [x] PDF (inlcuding encrypted)
- [x] HTML
- [x] CSV
- [x] XML
- [x] Microsoft Office (DOCX, PPTX, XLSX)
- [x] OpenDocument (ODT, ODS)

**Features:**
- [x] Barcodes (using Barcode4J)
- [x] Images
- [x] JFreeChart Charts
- [x] Embedded Fonts

**Comment by Postremus** [comment]
Fonts

Melloware ***@***.***> schrieb am Sa., 19. Okt. 2024, 17:06:

**Comment by melloware** [comment]
I think i have fonts already working unless you have a specific use case i can add an Integration Test?

**Comment by Postremus** [comment]
Basically, shipping your own font files for pdfs, and providing application
default fonts based o. Font files. There are a few settings to take, I can
look at my codebase on Tuesday ( currently PTO). Most interesting, if it
works correctly with class loading. Native, no idea if the font files need
to be marked as unremovable or something.

Melloware ***@***.***> schrieb am Sa., 19. Okt. 2024, 20:23:

**Comment by melloware** [comment]
Got it i just need to use this demo as an integration test: https://github.com/TIBCOSoftware/jasperreports/tree/master/demo/samples/fonts

**Comment by nderwin** [comment]
Maybe chart customizer classes, but that can wait until after a 1.0.0 release for me.

**Comment by melloware** [comment]
I think we should pick the most popular one to support. Maybe JFreeChart?

**Comment by nderwin** [comment]
That was surprisingly easy (#139)...  probably too easy.
