### ISSUE TITLE
Only Compile reports that have changed

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-jasperreports#144]
Check if the `.jasper` exists and if its date is older than the `.jrxml` file and only recompile then.

cc @nderwin

**Comment by nderwin** [comment]
I was finally able to test this, and noticed that all of the style files are copied when report file changes are detected.  It does only compile the file that changed as expected.

**Comment by nderwin** [comment]
I was testing in dev mode.

**Comment by melloware** [comment]
OK let me open another ticket to only copy the styles if they have changed as well.
