### ISSUE TITLE
Add support loading compiled jasper reports and corresponding resourcefiles from "external" directory

### ISSUE THREAD

**Issue by joggl71xpt** [quarkiverse/quarkus-jasperreports#167]
The current solution of v1.0.2 works fine if you put all your jrxml files + resources (like translation files) inside the generated jar file.

But this means, you need to build always a new version, if you want to make some changes in some templates.

Better solution would be, to have the possibility to define some "external" folder, which can be mapped via docker volumes. jasperreport will than "load" all stuff from this external folder. In my opinion it is even fine, to have in this external folder only pre compiled *.jasper files. (compiling of jrxml files will anyway not work in an native environment because of missing javacompiler).

The problem what I see at the moment, how can the classloader load these external resources? So is there a possibility to solve this ?

**Comment by melloware** [comment]
I assume this property doesn't work because its Build Time not run time: https://docs.quarkiverse.io/quarkus-jasperreports/dev/index.html#quarkus-jasperreports_quarkus-jasperreports-build-source

**Comment by joggl71xpt** [comment]
probably not, because this folder is only visible "inside" of the jar file, or ? we need an folder, which is part of the surrounding "docker container" ?!

**Comment by melloware** [comment]
Ahhh i see so if you had  `quarkus.jasperreports.build.source=/home/etc/yourdir` it is assuming that is a SubDir of the project.

**Comment by melloware** [comment]
we might be able to fix that

**Comment by melloware** [comment]
@all-contributors add @joggl71xpt  for bug,test

**Comment by melloware** [comment]
@joggl71xpt 1.0.3 is deployed can you try it? It should fix this issue and adds JasperFunctions to the pom.xml
