### ISSUE TITLE
[Help] Initial Setup

### ISSUE THREAD

**Issue by pinguim16** [quarkiverse/quarkus-jasperreports#184]
Hello everything is fine?
This is the first time I use quarkus-jasperreports, but try running the project I have the error below, I have read the documentation and found nothing recommended. Could you help me or instruct me on how to perform this configuration?

Error happens when I run maven
io.quarkiverse.jasperreports.config.ReportBuildTimeConfig.<init>()
![image](https://github.com/user-attachments/assets/91c7c021-afcd-4143-896f-70c9b2b4bdc6)

**Comment by melloware** [comment]
What version of Quarkus are you using?

**Comment by pinguim16** [comment]
2.7.6.Final-redhat-00006
