### ISSUE TITLE
GraalVM compatibility

### ISSUE THREAD

**Issue by Postremus** [quarkiverse/quarkus-jasperreports#22]
- [x] CSV 
- [x] XML 
- [x] HTML 
- [x] RTF
- [x] XLSX
- [x] PPTX
- [x] DOCX
- [x] ODT
- [x] XLS
- [x] Jasper DejaVu Font
- [x] PDF

**Comment by melloware** [comment]
Update. I have everything but PdF working in native but going to work on that tomorrow.
