### ISSUE TITLE
configuration for report file locations

### ISSUE THREAD

**Issue by nderwin** [quarkiverse/quarkus-jasperreports#72]
It would be nice to have a configuration setting that gave the location of the report files in a project.  By default, this could be `src/main/resources/jasperreports` similar to where Qute stores it's templates.  Ideally, it would be `src/main/jasperreports`, and then the compiled reports (`.jasper`) would be added to the final artifact instead of the `.jrxml` files.

**Comment by melloware** [comment]
I like this idea!  Are you going to work on this one @nderwin ?

**Comment by nderwin** [comment]
I'd like to, after I get #70 done.

**Comment by melloware** [comment]
OK i assigned to you.

**Comment by nderwin** [comment]
Fixed with #98
